//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplePay.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    
    public partial class Bestellung
    {
        public Bestellung()
        {
            this.Bestellposition = new HashSet<Bestellposition>();
            this.Rechnung = new HashSet<Rechnung>();
        }
    
        public int b_id { get; set; }
        public System.DateTime datum { get; set; }
        public System.TimeSpan uhrzeit { get; set; }
        public int k_id { get; set; }
        public int mwst_id { get; set; }
        public int m_id { get; set; }
        public int kt_id { get; set; }
    
        public virtual ICollection<Bestellposition> Bestellposition { get; set; }
        [JsonIgnore]
        public virtual Kunde Kunde { get; set; }
        public virtual Kunde_Tisch Kunde_Tisch { get; set; }
        [JsonIgnore]
        public virtual Mitarbeiter Mitarbeiter { get; set; }
        [JsonIgnore]
        public virtual MwSt_Satz MwSt_Satz { get; set; }
        [JsonIgnore]
        public virtual ICollection<Rechnung> Rechnung { get; set; }
    }
}
