//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplePay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkt_Zusatz
    {
        public int pz_id { get; set; }
        public int p_id { get; set; }
        public int z_id { get; set; }
    
        public virtual Produkt Produkt { get; set; }
        public virtual Zusatz Zusatz { get; set; }
    }
}
