//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplePay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkt
    {
        public Produkt()
        {
            this.Bestellposition = new HashSet<Bestellposition>();
            this.Produkt_Kategorie = new HashSet<Produkt_Kategorie>();
            this.Produkt_Zusatz = new HashSet<Produkt_Zusatz>();
        }
    
        public int p_id { get; set; }
        public string bezeichnung { get; set; }
        public double preis { get; set; }
        public int mengeneinheit { get; set; }
        public System.DateTime eingetragen_am { get; set; }
        public Nullable<System.DateTime> geaendert_am { get; set; }
    
        public virtual ICollection<Bestellposition> Bestellposition { get; set; }
        public virtual ICollection<Produkt_Kategorie> Produkt_Kategorie { get; set; }
        public virtual ICollection<Produkt_Zusatz> Produkt_Zusatz { get; set; }
    }
}
