//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplePay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tagesangebot
    {
        public Tagesangebot()
        {
            this.Tagesangebot_Produkt = new HashSet<Tagesangebot_Produkt>();
        }
    
        public int ta_id { get; set; }
        public string bezeichnung { get; set; }
        public double preis { get; set; }
    
        public virtual ICollection<Tagesangebot_Produkt> Tagesangebot_Produkt { get; set; }
    }
}
