//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplePay.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class Tagesangebot_Produkt
    {
        public int tap_id { get; set; }
        public int ta_id { get; set; }
        public int p_id { get; set; }
    
        public virtual Produkt Produkt { get; set; }
        [JsonIgnore]
        public virtual Tagesangebot Tagesangebot { get; set; }
    }
}
