//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestellposition
    {
        public int bp_id { get; set; }
        public int menge { get; set; }
        public System.DateTime datum { get; set; }
        public System.TimeSpan uhrzeit { get; set; }
        public int p_id { get; set; }
        public int b_id { get; set; }
    
        public virtual Bestellung Bestellung { get; set; }
        public virtual Produkt Produkt { get; set; }
    }
}
