//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mitarbeiter
    {
        public Mitarbeiter()
        {
            this.Bestellung = new HashSet<Bestellung>();
        }
    
        public int m_id { get; set; }
        public string vorname { get; set; }
        public string nachname { get; set; }
        public string nutzername { get; set; }
        public byte[] passwort { get; set; }
        public System.DateTime eingetragen_am { get; set; }
        public Nullable<System.DateTime> geaendert_am { get; set; }
        public int ro_id { get; set; }
    
        public virtual ICollection<Bestellung> Bestellung { get; set; }
        public virtual Rolle Rolle { get; set; }
    }
}
