//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SimplePay_HaendlerdatenEntities : DbContext
    {
        public SimplePay_HaendlerdatenEntities()
            : base("name=SimplePay_HaendlerdatenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bestellposition> Bestellposition { get; set; }
        public virtual DbSet<Bestellung> Bestellung { get; set; }
        public virtual DbSet<Kategorie> Kategorie { get; set; }
        public virtual DbSet<Kunde> Kunde { get; set; }
        public virtual DbSet<Kunde_Tisch> Kunde_Tisch { get; set; }
        public virtual DbSet<Mitarbeiter> Mitarbeiter { get; set; }
        public virtual DbSet<MwSt_Satz> MwSt_Satz { get; set; }
        public virtual DbSet<Produkt> Produkt { get; set; }
        public virtual DbSet<Produkt_Kategorie> Produkt_Kategorie { get; set; }
        public virtual DbSet<Produkt_Zusatz> Produkt_Zusatz { get; set; }
        public virtual DbSet<Rechnung> Rechnung { get; set; }
        public virtual DbSet<Rolle> Rolle { get; set; }
        public virtual DbSet<Tagesangebot> Tagesangebot { get; set; }
        public virtual DbSet<Tagesangebot_Produkt> Tagesangebot_Produkt { get; set; }
        public virtual DbSet<Tisch> Tisch { get; set; }
        public virtual DbSet<Zusatz> Zusatz { get; set; }
    }
}
