//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkt_Zusatz
    {
        public int pz_id { get; set; }
        public int p_id { get; set; }
        public int z_id { get; set; }
    
        public virtual Produkt Produkt { get; set; }
        public virtual Zusatz Zusatz { get; set; }
    }
}
