//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tisch
    {
        public Tisch()
        {
            this.Kunde_Tisch = new HashSet<Kunde_Tisch>();
        }
    
        public int t_id { get; set; }
        public string bezeichnung { get; set; }
        public System.DateTime eingetragen_am { get; set; }
    
        public virtual ICollection<Kunde_Tisch> Kunde_Tisch { get; set; }
    }
}
